export const LOADING_START = "LOADING_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const USER_LOGIN_INITIATE = "USER_LOGIN_INITIATE"
export const SESSION_API_ERROR = "SESSION_API_ERROR"
export const SESSION_EXPIRE_ERROR = "SESSION_EXPIRE_ERROR"
export const EXCEPTION_ERROR = "EXCEPTION_ERROR"
export const RESET_EXCEPTION_ERROR = "RESET_EXCEPTION_ERROR"

